export const ADD_ICON = '/client/assets/imgs/add.svg';
export const ACCOUNT_ICON = '/client/assets/imgs/account.svg';
export const ARROW_BACK_ICON = '/client/assets/imgs/arrow_back.svg'; //
export const CANCEL_ICON = '/client/assets/imgs/cancel.svg'; //
export const ARROW_FORWARD_ICON = '/client/assets/imgs/arrow_forward.svg';
export const CATEGORY_ICON = '/client/assets/imgs/category.svg';
export const CHAT_BUBBLE_MINI_ICON = '/client/assets/imgs/chat_bubble_mini.svg';
export const DONE_ICON = '/client/assets/imgs/done.svg';
export const EXIT_ICON = '/client/assets/imgs/exit.svg';
export const EXPAND_MORE_ICON = '/client/assets/imgs/expand_more.svg';
export const FAVORITE_BORDER_MINI_ICON =
	'/client/assets/imgs/favorite_border_mini.svg';
export const FAVORITE_BORDER_ICON = '/client/assets/imgs/favorite_border.svg';
export const FAVORITE_ICON = '/client/assets/imgs/favorite.svg';
export const IMAGE_ICON = '/client/assets/imgs/iamge.svg';
export const LOCATION_ICON = '/client/assets/imgs/location.svg';
export const MENU_ICON = '/client/assets/imgs/menu.svg';
export const MORE_VERT_ICON = '/client/assets/imgs/more_vert.svg';
export const SEND_ICON = '/client/assets/imgs/send.svg';
