export const ADD_ICON = '/icons/add.svg';
export const ACCOUNT_ICON = '/icons/account.svg';
export const ARROW_BACK_ICON = '/icons/arrow_back.svg'; //
export const CANCEL_ICON = '/icons/cancel.svg'; //
export const ARROW_FORWARD_ICON = '/icons/arrow_forward.svg';
export const CATEGORY_ICON = '/icons/category.svg';
export const CHAT_BUBBLE_MINI_ICON = '/icons/chat_bubble_mini.svg';
export const DONE_ICON = '/icons/done.svg';
export const EXIT_ICON = '/icons/exit.svg';
export const EXPAND_MORE_ICON = '/icons/expand_more.svg';
export const FAVORITE_BORDER_MINI_ICON = '/icons/favorite_border_mini.svg';
export const FAVORITE_BORDER_ICON = '/icons/favorite_border.svg';
export const FAVORITE_ICON = '/icons/favorite.svg';
export const IMAGE_ICON = '/icons/iamge.svg';
export const LOCATION_ICON = '/icons/location.svg';
export const MENU_ICON = '/icons/menu.svg';
export const MORE_VERT_ICON = '/icons/more_vert.svg';
export const SEND_ICON = '/icons/send.svg';
